name: adsimilamus
homepage: https://github.com/Ampless/Adsimilamus

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  args: ^2.3.0
  dsb_server: ^0.1.1
  dsbuntis: ^7.0.0-alpha.0
  path: ^1.8.0
  shelf: ^1.2.0

dev_dependencies:
  lints: ^1.0.1
