name: Build and publish a new container

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.2.0
      - uses: docker/setup-buildx-action@v1.6.0
      - uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.7.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm,linux/ppc64le,linux/s390x
          tags: chrissx/adsimilamus:latest
